### ISSUE TITLE
Can't scroll servers

### ISSUE THREAD

**Issue by gibby9er9er0** [SlippingGittys-Discord-Themes/Diskette#10]
Using the latest version of Vencord I decided to try some themes and Diskette was among them and I love it! However its currently unusable as there is no way for me to scroll through the servers I'm in as mouse scroll doesn't do anything

**Comment by ghost** [comment]
hello @gibby9er9er0 is this still an issue after 768e8e7? please check using the latest theme css, explanation on how to use it is in the readme

**Comment by ghost** [comment]
i'm not able to reproduce this after my last commits so i'll close this issue. please make a comment if it still persists
