### ISSUE TITLE
Doesn't work with Vesktop.

### ISSUE THREAD

**Issue by plyght** [SlippingGittys-Discord-Themes/Diskette#15]
![image](https://github.com/user-attachments/assets/7412cff3-7069-4319-91dd-b4f22c0da377)

I believe this is due to there being a space in the link. Any fixes?

**Comment by TacticalDeux** [comment]
huh, that's weird, I'm on vesktop too and it works alright for me
![image](https://github.com/user-attachments/assets/597f96c0-66e5-4b18-9724-41a305027607)

**Comment by ghost** [comment]
i can't replicate this, does `https://slippinggittys-discord-themes.github.io/Diskette/Diskette.theme.css` work?

edit: i just tested it on my mac (just in case it was a mac problem) with vesktop and the original link works also. something might be wrong with your vesktop installation - is it up to date?

**Comment by plyght** [comment]
> i can't replicate this, does `https://slippinggittys-discord-themes.github.io/Diskette/Diskette.theme.css` work?
> 
> edit: i just tested it on my mac (just in case it was a mac problem) with vesktop and the original link works also. something might be wrong with your vesktop installation - is it up to date?

@nvkomata yeah my vesktop is up to date.

The issue could be that i'm on MacOS Sequoia DB3 (Developer Beta 3) and i have been having some issues with wifi and other network related issues.

It also doesn't work with normal Discord with the Vencord injector.

**Comment by plyght** [comment]
> huh, that's weird, I'm on vesktop too and it works alright for me ![image](https://private-user-images.githubusercontent.com/66234915/350621090-597f96c0-66e5-4b18-9724-41a305027607.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NzM3NTYsIm5iZiI6MTcyMTU3MzQ1NiwicGF0aCI6Ii82NjIzNDkxNS8zNTA2MjEwOTAtNTk3Zjk2YzAtNjZlNS00YjE4LTk3MjQtNDFhMzA1MDI3NjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDE0NTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNDNmMDg3ZDA1MjA3MWNlNWRkNjk3ZTU4M2I2N2U0ZDExYWRkOWU5ODBlYWQ5YjUwOGVkNTA1ZThiMjBhYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JOTN2kDvw99aoV3qwBcc0Sn0HrCWusfFtC2thTjp_ck)

@TacticalDeuce it could be that you're on windows and i'm not.

**Comment by ghost** [comment]
> The issue could be that i'm on MacOS Sequoia DB3 (Developer Beta 3) and i have been having some issues with wifi and other network related issues.


i'd guess it's a problem related to your network issues, sorry that i can't help you here
