### ISSUE TITLE
Bar not fitting icons fully.

### ISSUE THREAD

**Issue by HerXayah** [SlippingGittys-Discord-Themes/Diskette#2]
![image](https://github.com/SlippingGittys-Discord-Themes/Diskette/assets/45071533/dfe81dec-dff5-4e15-8476-70db29e7a8ad)

When using the Toggle Game Addon the bar wont be the right size

**Comment by SlippingGitty** [comment]
thank you for your report :3 

there are many things about this theme which are unfinished/need to be touched, and this is one of those things i plan to fix sooner than later. :D

**Comment by HerXayah** [comment]
> thank you for your report :3
> 
> there are many things about this theme which are unfinished/need to be touched, and this is one of those things i plan to fix sooner than later. :D

I didnt knew i needed this theme until i saw it.

**Comment by SlippingGitty** [comment]
![image](https://github.com/SlippingGittys-Discord-Themes/Diskette/assets/76500838/dc5e4d7b-c181-4eee-8b6d-19cdce7fc4b6)

### iiiiiitttttttt shhhhhhould be fixed now :3

**Comment by HerXayah** [comment]
![image](https://github.com/SlippingGittys-Discord-Themes/Diskette/assets/45071533/0f50dccb-48ca-4a9a-8537-beed590e3e61)
