### ISSUE TITLE
Avatar Decorations missaligned with Platform Icons in Friend list

### ISSUE THREAD

**Issue by HerXayah** [SlippingGittys-Discord-Themes/Diskette#5]
![image](https://github.com/SlippingGittys-Discord-Themes/Diskette/assets/45071533/860a5c65-8c60-4260-906b-57cdbea215c6)

**Comment by HerXayah** [comment]
i think its a general issue with platform icons ngl
![image](https://github.com/SlippingGittys-Discord-Themes/Diskette/assets/45071533/713b10da-217c-4eb3-87f3-a741c62f6948)

**Comment by SlippingGitty** [comment]
I can replicate this, I will figure out solutions soon-- sorry about that :c

**Comment by HerXayah** [comment]
> I can replicate this, I will figure out solutions soon-- sorry about that :c

no worries lol

**Comment by ghost** [comment]
no longer an issue after rewrite
