### ISSUE TITLE
The new Ascid header font makes forum difficult to read

### ISSUE THREAD

**Issue by BrookJeynes** [SlippingGittys-Discord-Themes/Diskette#9]
The new ascid font makes forums pretty unreadable.

![image](https://github.com/SlippingGittys-Discord-Themes/Diskette/assets/25432120/8825ad6d-0702-4806-8205-6531ee223aaa)

ps. forum page has no styling but I assumed it was just wip haha

**Comment by SlippingGitty** [comment]
will fix soon! thanks <3

**Comment by BrookJeynes** [comment]
@SlippingGitty no stress, thanks for the quick response :) This is an awesome theme so thanks for all the hard work!

**Comment by ghost** [comment]
fixed by not using the asciid font after rewrite
